name: Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PHP dependencies
        working-directory: ./src
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Start Sail containers
        working-directory: ./src
        run: |
          cp -n .env.example .env
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan jwt:secret
          ./vendor/bin/sail artisan key:generate
      - name: Run Tests
        working-directory: ./src
        run: ./vendor/bin/sail test
      - name: Stop Sail
        working-directory: ./src
        run: ./vendor/bin/sail down
