name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Sail containers
        working-directory: ./src
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan jwt:secret
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force --seed

      - name: Run Tests
        run: ./vendor/bin/sail test

      - name: Stop Sail
        run: ./vendor/bin/sail down
